# Site settings
title: Malabya Tewari - Drupal, Devops & Web.
email: imalabya@gmail.com
description: Full Stack Developer & Technical Architect at Valuebound.
baseurl: ""
url: "http://imalabya.github.io"
twitter_username: malavya88
github_username:  malabya
gplus_username: imalabya
facebook_username: malabya88

assets:
  sources:
    - _assets/fonts
    - _assets/js
    - _assets/stylesheets

disqus:
  shortname: imalabya
google_analytics: UA-77169671-1

collections:
  projects:
    output: true
    permalink: /projects/:path

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
permalink: pretty
paginate: 10

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, rouge]
