# Site settings
title: Malabya Tewari
header-img: img/home-bg.jpg
email: imalabya@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Drupal developer, Open source enthusiast, trainer, blogger from Bangalore."
baseurl: ""
url: "http://imalabya.github.io"
twitter_username: malabya88
github_username:  imalabya
facebook_username:  malabya88
email_username:  imalabya@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
